### ISSUE TITLE
Empty page after install

### ISSUE THREAD

**Issue by XPEXT** [JustyleR/smsCMS#10]
So i have amxbans installed already.

I installed this smsCMS but after instalation it redirects to
"mywebsiteurl".com/home or other "mywebsiteurl".com/urlsettingwhichiwroteininstalation

And it allways shows empty page.

I checked database and i see new tables created.

What can be the issue?

**Comment by JustyleR** [comment]
Do you have the .htaccess file downloaded?
Do you have "/" and the end of your url in the config file. It has to be something like this: www.siteurl/sms/.

Sorry that I'm late with the respond.

**Comment by XPEXT** [comment]
My website structure

www.domain.com/amxbans
www.domain.com/amxbans/sms

When i installed this sms system i wrote in URL windows "www.domain.com/amxbans/sms/"

Everything went fine.

When i visit "www.domain.com/amxbans/sms/" i get redirected to "www.domain.com/amxbans/sms/home" and thats empty page.

Where should i put .htaccess file?

I did put .htaccess file here.
www.domain.com/amxbans/sms
www.domain.com/

**Comment by JustyleR** [comment]
Well.. The problem was that he didn't have mod_rewrite enabled.
