### ISSUE TITLE
Error after i've installed the script

### ISSUE THREAD

**Issue by Niiicu** [JustyleR/smsCMS#15]
After i installed the script, i have this error and i don't know how to fix it.

"The settings table is empty! Please reinstall the system!"

**Comment by stfkolev** [comment]
Could you provide a bit more information?

PS:
I figured it out. It is possible that your SQL did miss the insert into settings. Try inserting the following SQL into your database directly.

```
INSERT INTO `settings` (`template`, `language`, `site_title`, `md5_enc`, `reloadadmins`, `servID1`, `servID2`, `servID3`, `servID4`, `balance1`, `balance2`, `balance3`, `balance4`, `allow_sms`, `allow_paypal`, `unban_price`, `paypal_type`, `paypal_logs`, `paypal_email`) VALUES
('bootstrap', 'en', 'Counter-Strike SMS CMS by JustyleR', 1, 1, 29, 0, 0, 0, 1.20, 0.00, 0.00, 0.00, 1, 0, 5.00, 0, 0, '');
```

**Comment by JustyleR** [comment]
> Could you provide a bit more information?
> 
> PS:
> I figured it out. It is possible that your SQL did miss the insert into settings. Try inserting the following SQL into your database directly.
> 
> ```
> INSERT INTO `settings` (`template`, `language`, `site_title`, `md5_enc`, `reloadadmins`, `servID1`, `servID2`, `servID3`, `servID4`, `balance1`, `balance2`, `balance3`, `balance4`, `allow_sms`, `allow_paypal`, `unban_price`, `paypal_type`, `paypal_logs`, `paypal_email`) VALUES
> ('bootstrap', 'en', 'Counter-Strike SMS CMS by JustyleR', 1, 1, 29, 0, 0, 0, 1.20, 0.00, 0.00, 0.00, 1, 0, 5.00, 0, 0, '');
> ```

Most likely
